version: '2'
services:
  postgres-server:    # The Postgres Database Service
    image: postgres:latest
    restart: always
    environment:   # Username, password and database name variables
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix-bdd-password
      POSTGRES_DB: zabbix
      PG_DATA: /var/lib/postgresql/data/pgdata #data storage
    volumes:
      - /var/lib/postgresql/datacd
      
  zabbix-server:     # The main Zabbix Server Software Service
    image: zabbix/zabbix-server-pgsql:ubuntu-latest
    restart: always
    environment:   # The Postgres database value variable
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix-bdd-password
      POSTGRES_DB: zabbix
      ZBX_HISTORYSTORAGETYPES: log,text #Zabbix configuration variables
      ZBX_DEBUGLEVEL: 1
      ZBX_HOUSEKEEPINGFREQUENCY: 1
      ZBX_MAXHOUSEKEEPERDELETE: 5000
      ZBX_STARTVMWARECOLLECTORS: 10
      ZBX_VMWAREFREQUENCY: 30
      ZBX_VMWAREPERFFREQUENCY: 30
      ZBX_VMWARECACHESIZE: 16M
      ZBX_VMWARETIMEOUT: 10
    depends_on:
      - postgres-server
    ports:
      - 10051:10051
    volumes:  # Volumes for scripts and related files you can add
      - /usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts
  
  zabbix-web:    # The main Zabbix web UI or interface 
    image: zabbix/zabbix-web-nginx-pgsql:ubuntu-latest
    restart: always
    environment:  # Postgre database variables
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix-bdd-password
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: zabbix-server  # Zabbix related and Php variables
      ZBX_POSTMAXSIZE: 64M
      PHP_TZ: "Europe/Paris"  
      ZBX_MAXEXECUTIONTIME: 500
    depends_on:
      - postgres-server
      - zabbix-server
    ports:    # Port where Zabbix UI is available
      - 8090:80
      
  zabbix-agent:   # Zabbix agent service that tracks usage and send to zabbix server
    image: zabbix/zabbix-agent:latest
    privileged: true   #access mode for allowing resource access
    network_mode: "host"
    restart: unless-stopped
    environment:
      - ZBX_SERVER_HOST=ip-adress-zabbix #the IP/Dns of Zabbix server
      
  adminer:  #Optional for accessing databases
    image: adminer
    restart: always
    ports:
      - 8080:8080
      
  grafana-xxl:  #optional more functional and creative UI 
    image: monitoringartist/grafana-xxl:latest
    restart: always
    environment: 
     - GF_PANELS_DISABLE_SANITIZE_HTML=true 
    ports:
     - 3000:3000
