version: '2'
services:
  zabbix-proxy:    # The Postgres Database Service
    image: zabbix/zabbix-proxy-sqlite3:ubuntu-4.4-latest
    restart: always
    environment:   # Username, password and database name variables
      ZBX_PROXYMODE: 1
      ZBX_HOSTNAME: ZABBIX_PROXY_HOSTNAME
      ZBX_SERVER_HOST: ZABBIX_HOST_IP
      ZBX_ENABLEREMOTECOMMANDS: 1
      ZBX_STARTPINGERS: 1
      ZBX_STARTPOLLERS: 5
      ZBX_IPMIPOLLERS: 1
      ZBX_STARTPOLLERSUNREACHABLE: 1
      ZBX_STARTTRAPPERS: 5
      ZBX_STARTPINGERS: 1
      ZBX_STARTDISCOVERERS: 1
      ZBX_STARTHTTPPOLLERS: 1
      ZBX_STARTVMWARECOLLECTORS: 10
      ZBX_VMWAREFREQUENCY: 60
      ZBX_VMWAREPERFFREQUENCY: 60
      ZBX_VMWARECACHESIZE: 8M
      ZBX_VMWARETIMEOUT: 10
      ZBX_ENABLE_SNMP_TRAPS: true
    ports:
      - 10051:10051